/* SPDX-License-Identifier: AGPL-3.0-or-later */
export const INIT = "INIT";

export const SCARICA_CONFIGURAZIONE = 'SCARICA_CONFIGURAZIONE';
export const SCARICA_CONFIGURAZIONE_ERRORE = 'SCARICA_CONFIGURAZIONE_ERRORE';
export const SCARICA_CONFIGURAZIONE_SUCCESSO = 'SCARICA_CONFIGURAZIONE_SUCCESSO';

export const SCARICA_DATI_OPERATORE = 'SCARICA_DATI_OPERATORE';
export const SCARICA_DATI_OPERATORE_ERRORE = 'SCARICA_DATI_OPERATORE_ERRORE';
export const SCARICA_DATI_OPERATORE_SUCCESSO = 'SCARICA_DATI_OPERATORE_SUCCESSO';

export const SET_I18N = 'SET_I18N';

export const PASSWORD_AGGIORNATA = 'PASSWORD_AGGIORNATA';
export const EFFETTUA_LOGIN = 'EFFETTUA_LOGIN';
export const EFFETTUA_LOGIN_ERRORE = 'EFFETTUA_LOGIN_ERRORE';
export const EFFETTUA_LOGIN_SUCCESSO = 'EFFETTUA_LOGIN_SUCCESSO';

export const EFFETTUA_LOGOUT = 'EFFETTUA_LOGOUT';

export default {
    INIT,
    SCARICA_CONFIGURAZIONE,
    SCARICA_CONFIGURAZIONE_ERRORE,
    SCARICA_CONFIGURAZIONE_SUCCESSO,
    SCARICA_DATI_OPERATORE,
    SCARICA_DATI_OPERATORE_ERRORE,
    SCARICA_DATI_OPERATORE_SUCCESSO,
    SET_I18N,
    PASSWORD_AGGIORNATA,
    EFFETTUA_LOGIN,
    EFFETTUA_LOGIN_ERRORE,
    EFFETTUA_LOGIN_SUCCESSO,
    EFFETTUA_LOGOUT
}
